<style>
	.c3s-edit-link:after {
		content: "Edit";
	}
</style>

<h3>Manual edit URLs</h3>
<ul>
<#list api.query("person").findAll() as person>
	<li><a target="_blank" href="${person.editUrl}">Edit ${person.getText("name")}</a></li>
</#list>
</ul>

<h3>Autogenerated edit URLs</h3>
<ul>
<#list api.query("person").findAll() as person>
	<li data-c3s-id="${person.id}">${person.getText("name")}</li>
</#list>
</ul>